### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by staceyastewart** [movableink/movable-cli#37]
I've had this happen once before and then again today, where I create a new app and start working on it and then when I run the server, I get a syntax error in the HTML (even though I haven't changed anything on that page):

![image](https://user-images.githubusercontent.com/25775022/40084523-644699a0-5865-11e8-8fbc-d12c315fff12.png)

![image](https://user-images.githubusercontent.com/25775022/40084554-7cac4a44-5865-11e8-971e-5cf9a65c4559.png)

**Comment by mnutt** [comment]
I think this should be fixed by https://github.com/movableink/movable-cli/pull/38.
