### ISSUE TITLE
Hitting Cmd Z to Undo in the Cold State wipes changes

### ISSUE THREAD

**Issue by staceyastewart** [movableink/movable-cli#42]
While I was creating a cold state in the MDK UI, I hit CMD+z out of habit to undo, but instead of undoing my last move it undid everything I had done since my last save. I would assume most people are in the habit of hitting CMD+z to undo the most recent change so maybe this is something we could change.

**Comment by mnutt** [comment]
Thanks! Fixed by https://github.com/movableink/canvas/commit/c04838b45fd5eec6ef2519b3cc433c953b82c84a.
