### ISSUE TITLE
Select Menus Colliding 

### ISSUE THREAD

**Issue by staceyastewart** [movableink/movable-cli#43]
I started by running `movable new` and then removed the auto-populated `background-color` select menu from the manifest and create two new select menus. However, they all seem to be colliding in the MDK UI. The options from the `background-color` drop-down that is deleted seem to be showing up, and the UI for the options isn't matching the code.

**Comment by mnutt** [comment]
Fixed by https://github.com/movableink/canvas/commit/fa60314e687dc1ce2919aef5cc82ff50e0220bc8.
