### ISSUE TITLE
Parity between platform and MDK

### ISSUE THREAD

**Issue by jeffreydu** [movableink/movable-cli#45]
Not a pressing matter but I noticed that interface in the MDK still looks like the old one. Would be nice if the two versions can stay updated.

Platform:
![image](https://user-images.githubusercontent.com/18515434/42959917-534c19ba-8b58-11e8-8238-6c4b3324dab2.png)

MDK:
![image](https://user-images.githubusercontent.com/18515434/42960033-b643d9cc-8b58-11e8-9e46-6aac16b73b56.png)

**Comment by mnutt** [comment]
100%, I'm working on an update either at the end of this week or beginning of next.
