### ISSUE TITLE
Removing query parameters in Settings Tab doesn't update manifest

### ISSUE THREAD

**Issue by iamplo** [movableink/movable-cli#46]
MDK 0.16.2
Steps to reproduce

1. Settings > Add Query Parameter > Save
2. Delete query parameter > Save
3. Check manifest, you'll notice the query param is still listed
4. Reload Settings page, query parameter that you deleted is present.

**Comment by mnutt** [comment]
Thanks! Fixed by https://github.com/movableink/canvas/commit/1baa2bb1e9b0df00e41f1bdcf3310a56a9b0c773, live in prod now.
