### ISSUE TITLE
Custom Fonts In Development

### ISSUE THREAD

**Issue by johnsigmon** [movableink/movable-cli#51]
When using custom fonts in development, it's necessary to hardcode the values into the index.html file.  When changes are made within the MDK UI the values are overwritten by the re-render.  Additionally, client-specific user fonts will not display in the rendered "Preview" pane, and the only way to check the display is creating an instance of the deployed app from within the client's account.  

Can we explore ways for us to upload custom fonts?

**Comment by mnutt** [comment]
Good news! This is resolved in #54.
