### ISSUE TITLE
Non-Existent Items Populating Tool Icon Dropdown

### ISSUE THREAD

**Issue by johnsigmon** [movableink/movable-cli#52]
I stumbled upon this by accident when I didn't remember to change the Tool Icon from the default `text-vector` on a build.  Everything runs fine locally but it throws an error (screenshot 1) upon deployment.  Upon further inspection of the error, it's attempting to match the icon from a list that's significantly smaller than the list of options in the interface.  Thinking maybe this is just a case of something populating this drop down that shouldn't.  I parsed out both lists and dropped in below.  When I changed the icon from `text-vector` to `align-bottom` (another option not in the list pulled from the error), I got the same error (screenshot2)

<img width="732" alt="screenshot1" src="https://user-images.githubusercontent.com/19255281/43657216-1a288746-9723-11e8-9732-981a19e5f12f.png">
<img width="736" alt="screenshot2" src="https://user-images.githubusercontent.com/19255281/43657217-1a37c13e-9723-11e8-91a5-f3fab0600581.png">

```
LIST OF ACCEPTABLE ICONS (based on assumption from deployment error)
avatar
bar-chart
barcode
calendar
cart
chatter
clock
code
copy
countdown-timer
countdown
external-link
globe
image-layer
image
images
instagram
local-time
maps
olapic
param
personal
picture
pie-chart
pin
pinterest
polling
proximity-pin
QR
rss
sharing
square
text-layer
text-tool
text
twitter-favorite
twitter-retweet
twitter-username
twitter
vector-square
vector-tool
video
weather-average
weather-city
weather-day
weather-description
weather-high-temp
weather-icon
weather
```

```
DROPDOWN OPTIONS IN MDK
QR
align-bottom
align-center
align-left
align-middle
align-right
align-top
arrange-center
arrange-left
arrange-right
arrows-select
avatar
bar-chart
barcode
bold-text
calendar
cart
chatter
clock
code
condensed-view
copy
countdown-timer
countdown
crop
cursor-grab
cursor-move
cursor
distribute-horizontal
distribute-vertical
dropdown-arrow
duplicate
expanded-view
external-link
globe
grab
image-layer
image
images
instagram
italic-text
local-time
locked
map-helper
maps
media-library
minus
move
olapic
param
personal
picture
pie-chart
pin
pinterest
plus
polling
proximity-pin
qr-code
redo
rotate
rss
settings
sharing
square
subscript-text
superscript-text
text-center
text-color
text-justify
text-layer
text-left
text-right
text-tool
text-vector
text
tools
trash
twitter-favorite
twitter-retweet
twitter-username
twitter
underline-text
undo
unlocked
vector-square
vector-tool
video
weather-average
weather-city
weather-day
weather-description
weather-high-temp
weather-icon
weather
workspace-barcode
workspace-favorites
workspace-instagram
workspace-olapic
workspace-picture
workspace-pinterest
workspace-qr-code
workspace-retweets
workspace-weather
```

**Comment by mnutt** [comment]
Sorry, we made some icon changes with unintended consequences. I've changed the dropdown to only show allowed icons now.
